- client/main.jsx
- imports/ui/AuthRedirect.jsx
- imports/ui/CUreviewsGoogleLogin.jsx
- imports/ui/Form.jsx
- imports/ui/Login.jsx
- server/methods.js
Google Login had become broken on Safari after enforcing HTTPS.  This was because Safari blocks the log-in pop-up by default.  In this commit, I have re-arranged the log-in workflow to use a series of redirects instead, allowing it to work with pop-up blockers and be more mobile-friendly.
Tested locally and will be testing in review app.
TODO:
This breaks adding users to the database when they update a review.  Very specific problem that will look to fix soon.  Essentially, the problem now is that since we redirect instead of use a callback function, we are not getting user's first and last name back from Google for some reason.
> Login redirect

- imports/ui/AuthRedirect.jsx
Fixes issue with regular expression support on Safari.  Problem was that Safari doesn't support "negative lookbehind" in regex's.  Changed to more supported "positive lookahead"
Tested on local Safari, will test on staging app and Safari mobile.
> Safari fix

- imports/ui/ClassView.jsx
- imports/ui/Form.jsx
The review form in the "Leave a review" pop-up had previously determined if it should submit a review for the course in classView or the course selected in the pop-up by "searchBar" prop. This pull request changes this decision to be made on whether session's "courseId" is undefined or not.
The "courseId" is set in a handler in the pop-up's search bar and set to undefined after the review is submitted, ensuring this does not interfere with regular reviews.
Also fixes bug where "enter" key when searching in a classview does not actually change the page to be the new class.
> Changed the course a review from pop-up is submitted for to depend on session, not props

- .meteor/packages
- imports/api/dbDefs.js
This PR fixes the issue that the API does not return a `access-control-allow-origin` header and therefore does not allow API requests from other applications.
Tested locally for the appearance of `access-control-allow-origin` header in Postman, will test in dev site, then deploy to prod.
> Add support for access-control-allow-origin header in API

- imports/api/dbDefs.js
Fixes the crashing site.  Bug was caused by using a new Meteor package `JsonRoutes` while not being able to explicitly import it (because it's a meteor package and not an NPM one).  In the future we are going to migrate to NPM packages only.
Tested locally, will test in dev site, then confirm on prod.
> Fix bug causing crash in API

- imports/ui/Navbar.jsx
- imports/ui/Results.jsx
- imports/ui/SearchBar.jsx
This feature adds the previously searched query to the search bar on a page
Went to start page. Placeholder text was still present. No default text seen. Searched for something. Verified that the correct query showed up.
> Insert previous query to searchbar

- LICENSE
Now that all CUReviews contributors have signed the CLA, this will license CUReviews under AGPL-3.0 to make the licensing consistent across the DTI repository. 
This does not impact the code at all and should not break anything
If we change this license in the future this will require permissions from all contributors again. 
None
> License CUReviews under AGPL-3.0

- client/package.json
- client/src/index.tsx
- client/src/jQuery.ts
- client/src/ui/Form.jsx
- yarn.lock
This PR removes jQuery as a dependency in `/client/index.ts` and therefore completely from the codebase
It was being used for a deprecated feature in a function that was no longer relevant - I've removed that function as well.
Tested typical workflow locally
> Remove jquery from deprecated code

- LICENSE
- README.md
- server/dbInit.test.ts
- server/dbInit.ts
- server/methods.ts
- server/server.ts
- server/shim.ts
Goal: After #145 , we don't know if our scraper works. This is an attempt to write a tested scraping implementation. The old one was also not easy to understand.
It's like #173, except our goal is to make to make a correcter scraping implementation rather than a faster scraping implementation. Fun Fact: Compared to the 15 mins it historically took, this is actually doing pretty well!
Frontend integration will be split out into a seperate PR.
All tests are in the file dbInit.test.ts. We create a mock endpoint, and then scrape from it. The scraper is split up into various utility functions, which are seperatly tested.
It was also tested on a clean db. You can also do so by running. This will automatically do everything for you. No need to fumble about with mongod or anything.
```bash …
```
> Improved Scraper 2

- client/src/ui/Review.jsx
This fixes the issue of empty helpful quantities on reviews.
Identified reviews locally with empty Helpful numbers. Then, I implemented my changes and verified that:
1. They now showed 0
2. Clicking over and over would update the number properly
3. The correct number was there after a refresh
Will test again on dev site using same criteria
> Blank helpful

- .gitignore
This pull request simply adds mongodb-binaries to .gitignore. I noticed that after running jest tests a folder called `mongodb-binaries` was created and tracked by git. I imagine we don't want these to be pushed to the repo.
> Added mongodb-binaries to .gitignore

- client/src/ui/CourseCard.tsx
- common/CourseCard.js
- server/methods.ts
This pull request removes weighting of COVID affected/virtual reviews differently than other reviews. It also refactors the course card to get class metric values based on the values in the DB rather than recalculating them.
Tested by locally creating and then reporting/removing reviews for classes with reviews and without reviews to see if metrics changed as expected on the front end at each step.
common/CourseCard.js should probably be split up; I think it no longer contains functions used by both the back end and the front end.
Changing how the front end gets the values for gauges has potential to cause errors but looks good from my testing.
> Remove virtual weight

- client/src/ui/Gauge.tsx
This pull request fixes issue #203. It simply resets the percentage of the gauge to 0 when there is no metric available, where as the percentage would stay the same before.
Tested by clicking through classes and verifying values and percentage filled was changed appropriately. I also checked that the gauges still loaded properly on individual class pages.
Clicking on class with reviews:
And then clicking on one with no reviews right after:
> Reset gauge percentage when value is NaN

- .gitignore
- cypress.json
- cypress/integration/reviews.spec.js
- cypress/plugins/index.js
- cypress/support/commands.js
- cypress/support/index.js
- cypress/utils.js
- debug.log
- server/package.json
- yarn.lock
This pull request adds the testing framework Cypress to CU Reviews. Having end to end tests will make spotting bugs easier as we look to make the site more maintainable in the future.  Cypress is similar to Selenium in that it performs automated actions on a live browser, but Cypress was built specifically for testing.  In addition to adding this framework, this PR adds a test that will catch #199 if it occurs again in the future.
Tested using dev site but the tests can be switched to production or local in the future.
To run the tests locally, first add Cypress: `yarn workspace server add cypress`. 
Then run` yarn run cypress open` to open the Cypress app and run tests.
> Add groundwork for end to end testing

- server/package.json
- server/server.ts
- yarn.lock
This PR fixes the issue where some users land on the `http://` version of CUReviews.  This leads to problems when submitting a review.
Plan to test on a PR deployment created by Heroku
- This _does not_ force HTTPS on localhost, do not expect this behavior
- Credz: https://medium.com/@seunghunsunmoonlee/how-to-enforce-https-redirect-http-to-https-on-heroku-deployed-apps-a87a653ba61e
> Force HTTPS connection

- server/endpoints.ts
- server/endpoints/Search.test.ts
- server/endpoints/Search.ts
- server/tsconfig.json
This pull request implements the rest of the publicly available endpoints for searching informatio about classes.
In accordance with some comments on, a previous PR, I changed the name from SearchBar to Search for this functionality.
See the additional tests in `Search.test.ts` for the endpoints that were added.
Creating this PR revealed an issue with mongodb we should look into some more. In particular, the question is about mongo's indexes, which are somehow tied implicitly to the db. We should move a way from this as it leads to subtly different behavior on testing/local/staging/prod. In particular, I think we should make it more explcit with something like this: https://www.npmjs.com/package/mongoose-text-search , but let me know what you guys think.
None yet, deprecation will be a …
> Create Remaining Search Bar Endpoints

- client/src/ui/CourseReviews.tsx
- server/endpoints.ts
- server/endpoints/Review.test.ts
- server/endpoints/Review.ts
- server/endpoints/SearchBar.test.ts
- server/endpoints/utils.ts
This pull request creates express endpoints for viewing reviews. Currently we have two meteor methods that do this: 
`getReviewsByCourseId` and `getReviewsByProfessor`. Doing a quick search through the project shows that `getReviewsByProfessor` is not used anywhere, so this PR will have `getReviewsByCourseId` and `getCourseById` (used in `getReviewsByCourseId`). Other endpoints for reviews that change data ex: makeVisible, reportReview are not included in this PR for viewing reviews.
Added tests in `server/endpoints/Review.test.ts`
Currently it seems like we are organizing endpoints by where they are used. EX: `getClassesByQuery` is used in `SearchBar` so we put it in `SearchBar.ts`. Looking through the meteor methods we have, however, I don't think such a method would work very well as …
> Express Endpoint for viewing Reviews

- server/endpoints.ts
- server/endpoints/Review.test.ts
- server/endpoints/Review.ts
- server/endpoints/Search.test.ts
- server/endpoints/Search.ts
- server/endpoints/utils.ts
This PR is another part of the long road to severing our dependence on the Meteor shim. It also tries to get rid of some of the bad code that is infiltrating our codebase as holdovers from methods.ts.
In particular, it added another method which (as far as I was able to tell) is the final one used for public accesses (i.e. not cornell student submission dependent). Let me know if there was one I missed.
Additionally, this PR removes the obsessive regex checking in some of the backend method. It adds nothing that is not provided in a better way by the guard pattern and express-validator. See the test in Reviews.test.ts which show that these features really do work as intended. Going forward, I think it makes sense to remove these regex checks if they can be replaced by equivalent code in …
> Odds and Ends, and wrapping up new public API

- server/endpoints.ts
- server/endpoints/AdminActions.test.ts
- server/endpoints/AdminActions.ts
- server/endpoints/Auth.ts
- server/endpoints/utils.ts
This pull request creates endpoints for the 5 Meteor methods that require admin authentication to carry out that are not stats dashboard related. It also adds unit tests where applicable and refactors Auth.ts to account for the new utils.ts folder.
Added unit tests in AdminActions.test.ts
Unit tests weren't added for the two professor functions because their functionality falls under behavior that should be tested in dbInit.test.ts. There aren't any unit tests for the underlying dbInit functions used already. I don't think there's much use in unit tests for those endpoints/functions, but I wanted to note in case it raised concerns.
> Express endpoints for admin authenticated endpoints

- client/src/ui/Results.jsx
- client/src/ui/SearchBar.jsx
- server/endpoints/AdminActions.test.ts
- server/endpoints/Search.ts
- server/methods.ts
This pull request replaces Meteor calls for getting classes by keyword/query on the front end. It also moves the getClassesByQuery Meteor method that uses regular expressions to the getClassesByQuery endpoint and moved its regular expression check to the endpoint's guard. 
- checked existing unit tests worked for getClassesByQuery endpoint
- Tested searching from home page, results page, course page
We should do thorough testing on the dev site again since searching is so essential to using the site.
N/A
> Client side uses search express

- client/src/ui/Statistics.tsx
Another 🧼 Code clean up day PR, this renames a function name in Statistics.tsx to be getHowManyEachClass from howManyEachClass. This improves clarity because there was also a member of state in this component named howManyEachClass.
Open admin page and waited for it to load as expected.
🧼 squeaky clean code
N/A
> Make function name in Statistics.tsx clearer

- client/src/ui/ProfessorResult.tsx
- client/src/ui/SearchBar.jsx
- client/src/ui/SubjectResult.tsx
This pull request is a code clean up that renames the subject and professor components, which had previously been named 'Course' in their tsx files and fixes the accompanying imports.
Tested searching by course, professor, and major.
N/A
> Fix subject and professor component names

- client/src/ui/FilteredResult.tsx
- client/src/ui/Gauge.tsx
This fixes issue #218 where CS 2110 had a huuuge decimal. It also applies the same fix to gauge values in case that comes up in the future.
Verified that classes' metrics from results and course page still looked good, both after searching and submitting reviews.
> Fixed rounding issue

- server/endpoints.ts
- server/endpoints/AdminActions.test.ts
- server/endpoints/AdminActions.ts
- server/server.ts
This PR migrates the last bit of backend functionality -- updateAllCourseMetrics, which does exactly what it sounds like.
Tested manually. Also added new test cases in `AdminActions.test.ts`
It also fixes the odd linter warning in endpoints.ts and a few other places.
Changed some of the return values in AdminActions to the new format they were supposed to be. The endpoints that the frontend used were still the old ones, but we should double check everything works just in case.
> Update all course metrics et. al.

- client/src/ui/Login.tsx
When the session token was null/undefined, this was not caught by the if statement that this PR changes, leading to failing backend call with empty data, that was then caught by the express guard, which then led to a HTTP error. This change forces the token to be initialized before the backend call.
Tested locally.
> Fix Admin Login Issue

- client/src/ui/Admin.jsx
- client/src/ui/CourseReviews.tsx
- client/src/ui/Form.jsx
- client/src/ui/Login.tsx
- client/src/ui/Results.jsx
- client/src/ui/ResultsDisplay.jsx
- server/endpoints.ts
- server/endpoints/AdminActions.test.ts
- server/endpoints/AdminActions.ts
- server/endpoints/Review.ts
- server/endpoints/Search.ts
This PR migrates the last bit of Meteor call functionality. In particular, these are some admin actions, some search related functionality, and the reporting functionality. There are all very similar.
It also adds some express endpoints for functions which seem to never have been called. We should look into whether or not we can ditch them.
Tested locally. Also adjusted backend tests where relevant.
There will need to be another PR to deprecate Meteor subscriptions. There will need to be then the final PR to disable meteor.
There were some Meteor calls to non-existent Meteor methods. These calls have been removed.
> Remove last frontend meteor calls

- server/endpoints/Search.ts
This pull request fixes search by professor by removing the '+' character from queries and switching to use a case insensitive regex.
Just did quick user testing for this.
> Fixing Search By Professor

- client/src/ui/Course.tsx
- client/src/ui/SearchBar.jsx
The search bar shows somewhat irrelevant search suggestions. For example, searching in our current production website exhibits two main issues:
1. the suggestions aren't sorted correctly and don't match with the search results on the `/results` page
2. searching the same term can lead to different suggestions depending on typing and network speed
Example of issue 1: Searching "operating systems" shows pretty irrelevant suggestions in the search bar, but the actual results returned in the `/results` page are much more relevant.
Example of issue 2: Typing in "2110" multiple times into the search bar leads to different suggestions each time.
| 1 | 2 | 3 |
| --- | --- | --- |
| ![image](https://user-images.githubusercontent.com/11168401/158096950-13c2baf1-0837-41dd-9435-7fd7f8c99ae8.png) | …
> Fix relevance of search bar suggestions

- server/dbInit.test.ts
- server/package.json
- yarn.lock
This pull request fixes the CI build issues related to uninitialized indexes on the testing instance of our database. Looking at the commit history on `master`, you can see that some commits fail to build due to this issue (see notes for part of the error output).
This changes the test runner for our Jest setup from `jasmine2` to `jest-circus`. This is the newer test runner for Jest (default since Jest 27), which we have to manually enable for our older version of Jest (Jest 24).
For more context on the process of fixing this issue, see [this Notion document](https://www.notion.so/cornelldti/Fix-deployments-and-testing-1476b3f259e049728d79e834ecb5c4de).
Tested using [`act`](https://github.com/nektos/act), which allows us to run GitHub Actions locally. 
Before the fixes, the CI actions …
> Fix CI tests using jest-circus test runner

- client/src/ui/ClassView.jsx
- client/src/ui/ClassViewNew.tsx
- client/src/ui/Form.jsx
- client/src/ui/Gauge.tsx
- client/src/ui/PreviewCard.jsx
- client/src/ui/RatingInput.tsx
- client/src/ui/ReviewForm.tsx
- client/src/ui/css/RatingInput.module.css
This PR implements different color scales in metric boxes and gauges. Colors are assigned based on these values:
Since Overall and Difficulty & Workload use different ranges, a new variable `isOverall` was added to `GaugeProps` and `RatingInputProps`. This `isOverall` is used along with the rating value to assign appropriate colors.
Here are 3 places with the reflected changes:
1. Gauges in class preview
2. Gauges in class view
3. Metric boxes in review form
The color codes used are as following:
- Red: hsl(4, 100%, 71%), rgba(225, 117, 108, 1), #FF756C
- Yellow: hsl(47, 94%, 58%), rgba(248, 204, 48, 1), #F8CC30
- Green: hsl(101, 64%, 43%), rgba(83, 178, 39, 1), #53B227
For hovering for metric boxes, above colors with 50% opacity were used:
- Red: rgba(225, 117, 108, 0.5), #e1756c80
- …
> Make Colors Change for Metric Boxes & Gauges

- client/src/ui/css/ClassView.css
- client/src/ui/css/ClassView.module.css
- client/src/ui/css/Form.css
- client/src/ui/css/ReviewForm.module.css
Work in Progress. 
This pull request is to revert the review form to not be sticky as currently on my_reviews_page, you need to scroll all the way down to the end of the reviews to submit a review of your own. 
Testing will compose of using different screen sizes and mobile, (etc). 
No added linter warnings.
> Reverting Reviews to Sticky

- client/src/modules/Course/Components/Course.tsx
This PR works on the broken course (temporarily) feature.
> Fix auth not working in Course page

- client/src/modules/Course/Components/Gauges.tsx
- client/src/modules/Course/Styles/Gauges.module.css
Helps mobile & tablet users of CUReviews go from 😠 to 👌 when looking at the ratings page for a course! Thanks to this PR, the summary card at the top of said ratings page is now responsive.
https://github.com/user-attachments/assets/5dfb223f-0913-4677-ac22-d53ea8a268f7
Drag around the window size & confirm that the summary / review info card is responsive / fully visible under `1216px` (compare with [the live version](https://cureviews.org) of CUReviews).
Zip
[gif](https://media2.giphy.com/media/v1.Y2lkPTc5MGI3NjExN3FkMnh5OTZnZ3k2YndjYzNhNnJ2NXhsMjI1bXlkb2hob3oxYm9vYiZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/PmABbbUe3IqUKSOIBV/giphy.webp)
> style: make review summary gauge card responsive

- client/src/modules/Globals/Styles/ProfileDropdown.module.css
this PR fixes the vertical length of the top-right profile dropdown!! (yet another one liner)
Tested on a variety of sizes/zooms.
this also seems like a fix that might be too simple, but it appears to work after simple testing
> Fix vertical height of profile dropdown

- client/src/modules/Globals/Styles/NavBar.module.css
This PR expands the navbar to full length. (Early contender for smallest PR of the semester?)
https://github.com/user-attachments/assets/03ef45ce-ef1e-4612-80ef-2c3f884e2aa3
Tested on a variety of dimensions and zoom factors.
This felt like too simple of a fix, but I can't figure out why the max-width was there in the first place -- any additional insight would be helpful!
> Removed max width of navbar

- client/src/modules/Results/Components/ResultsDisplay.jsx
- server/src/search/search.controller.ts
This PR works on the course search and results feature.
Search Bar:
Results:
No Results:
- Search up any course in frontend and both search and full result list should be sorted by course number when typing in the shortened subject code (e.g. CS, ECON, MATH, etc.)
- Uncheck all boxes in semester or level
- Sorted course by subject and professor list on backend
- Changed default sorting on results page to be more intuitive
- Updated rendering for no items that fit filters
> Updated Search/Results Sorting

- client/src/modules/Course/Components/PreviewReviewCard.tsx
- client/src/modules/Course/Components/ReviewCard.tsx
This PR sorts professors' names by first name in review cards for consistent internal ordering.
I did some before/after testing to make sure this works, but I can't imagine what bugs would be introduced by this change.
> Sort professor names in review cards

- client/src/modules/Course/Components/MultiSelect.tsx
- client/src/modules/Course/Components/ReviewModal.tsx
- client/src/modules/Course/Components/SingleSelect.tsx
- client/src/modules/Course/Styles/ReviewModal.module.css
When adding a lot of majors or resizing text window, modal is now scrollable with hidden scrollbar. 
https://github.com/user-attachments/assets/56f8d08d-8747-47e5-ab3a-d45de3654374
Tested on variety of screen sizes/modes, appears to function similarly on mobile and work more effectively on desktop.
Major options now appear from the top like the grades. They would previously spill off the modal screen, which is kinda ugly and also problematic when scrolling is involved. 
> Fix modal resizing

- client/src/modules/Course/Components/Course.tsx
- client/src/modules/Course/Styles/Course.module.css
This PR works on the filter by professor course page dropdown.
- [] 🎨 Style
https://github.com/user-attachments/assets/702f3af8-4f84-4440-ae53-e0308b45ea3a
Checked on different screen sizes, fixing styles as needed. Looks slightly awkward on mobile since the header brushes up against the text, but they never overlap. Checked on a variety of classes to ensure that all professors were added to the dropdown. 
[gif](https://giphy.com/gifs/talkshowgameshow-episode-19-talk-show-the-game-26DN0TFE3TXYJq70A)
> Filter by prof on course page

- .github/workflows/ci-policies.yml
- .github/workflows/ci-workflow.yml
- server/package.json
- yarn.lock
This PR works on the test feature.
Setting vitest dependency to 2.1.9, which fixed compatibility with testing (something was going on in newer versions of vitest). You may need to re-run `yarn` on your devices to update node_modules after pulling this change.
> Fixing testing error

- client/src/modules/SearchBar/Components/SearchBar.tsx
This PR works on the search bar feature.
Previously, due to an error in the order search results appear (profs -> subj -> classes), when you tab down with the down arrow, it would bounce around from subject back up to profs. You can test this on your own in the site by querying a major and see how it looks funny! Heres the issue page where Megan noticed: [https://www.notion.so/Backlog-List-11a0ad723ce180c7a2d0ef54951c96b7?p=1cf0ad723ce180aa9f99cafa945e49e3&pm=s](url)
Fixed this
> Fixed search bar order
