cornell-dti/cureviews

- README.md
- client/main.css
- client/main.jsx
- imports/api/classes.js
- imports/ui/App.jsx
- imports/ui/Course.jsx
- imports/ui/CourseCard.jsx
- imports/ui/CourseReviews.jsx
- imports/ui/Form.jsx
- imports/ui/Home.jsx
- imports/ui/Permalink.jsx
- imports/ui/PopularClasses.jsx
- imports/ui/RecentReview.jsx
- imports/ui/SearchBar.jsx
- imports/ui/css/SearchBar.css
- imports/ui/gaugeFile.js
- package-lock.json
- yarn.lock
Permalinks now populate in the search bar, and update in the browser accordingly.
Two things of note:
1. `modules.js?hash=0f9d80462bccb6202bffced7375d3da11f2fed2f:3851 Warning: validateDOMNesting(...): <a> cannot appear as a descendant of <a>. See App > a > ... > a.` I don't know where this error is occuring. I'll keep looking into where this is coming from.
2. Right now, the search bar populates the permalinks of courses, which takes some time to re-render the course from scratch instead of passing it to `<CourseCard>`. What I'd like to happen is that we have both the permalink from the search bar, and we pass the course information to `<CourseCard>` at the same time.
> Permalinks

- imports/ui/Course.jsx
- imports/ui/Permalink.jsx
- imports/ui/SearchBar.jsx
- imports/ui/css/Course.css
- imports/ui/css/SearchBar.css
show all search results in the course card, remove dependance on App file
> fix course card search

- imports/ui/App.jsx
- imports/ui/Permalink.jsx
- imports/ui/css/App.css
- imports/ui/css/SearchBar.css
styling for the navigation and search bars
> Nav and searchbar styling

- imports/ui/CourseCard.jsx
- imports/ui/Form.jsx
- imports/ui/Permalink.jsx
- imports/ui/SearchBar.jsx
- imports/ui/css/App.css
- imports/ui/css/Course.css
- imports/ui/css/Form.css
- imports/ui/css/RecentReview.css
- imports/ui/css/SearchBar.css
- package-lock.json
- package.json
- yarn.lock
> various styling fixes 

- imports/ui/SubjectLeaderboard.jsx
- imports/ui/css/Course.css
Numbers to the right of the subjects show the total number of reviews associated with that subject.
> Add numbers of reviews to subjects

- client/main.html
Changed meta data for fb promo
> Change of promo

- client/main.html
- Source: https://stackoverflow.com/a/8910877
> Replace HTTPS image with HTTP image URI

- imports/ui/css/App.css
Please test this on a safari browser to ensure it doesn't create any issues there! I tested it on chrome and it looks all good there.
> Fixed safari spacing issue

- imports/ui/SearchBar.jsx
Fixes issue #55  where autofill appears on Chrome when searching
> Fixed autocomplete popping up on Chrome

- .eslintignore
- .eslintrc.json
- .github/workflows/ci-workflow.yml
- package-lock.json
- package.json
Linting is very broken now so I have to suppress almost everything in .eslintignore. The fact that we currently pass the linter test does not mean we are in a good state. We should eventually remove everything in .eslintignore and make it still pass linter!
The code style is not consistent in the repo. We should fix the linter problems first, then enforce a consistent code style!
I only make the CI run linter because I can't figure out how to build the site.
See the CI run!
> Setup Linter and CI

- .eslintignore
- .eslintrc.json
- app.json
- imports/ui/Admin.jsx
- imports/ui/App.jsx
- imports/ui/Auth.jsx
- imports/ui/CUreviewsGoogleLogin.jsx
- imports/ui/ClassView.jsx
- imports/ui/Course.jsx
- imports/ui/CourseCard.jsx
- imports/ui/CourseReviews.jsx
- imports/ui/Form.jsx
- imports/ui/Login.jsx
- imports/ui/RecentReview.jsx
- imports/ui/Review.jsx
- imports/ui/SearchBar.jsx
- imports/ui/SubjectLeaderboard.jsx
- imports/ui/Template.jsx
- imports/ui/UpdateReview.jsx
- imports/ui/js/CourseCard.js
- imports/ui/seachTest.jsx
- server/dbInit.js
- server/methods.js
- server/publications.js
This commit fixes most of the easy syntactic problems and turn linter errors to warning to ensure at least we can have some non-failing jobs running on CI.
The goal for the future is to turn all warnings into errors and actually fix all these problems!
Major fixed problems:
- Change global variables to `let` and `const` as much as I can
- Change `var` variables to `let` and `const` as much as I can
- Remove unused imports and unused variables
- Add rel="noopener noreferrer" to fix security issues
- Removed some commented import.
Some js files are still ignored since they seem to be some third party library code. Not sure why they are checked into the repo.
👀 : mostly syntactic changes
Deployed heroku app looks good. Nothing broken there.
> Unignore linter errors and fix a lot of them

- client/main.html
Now https is enabled, we should be use https for og:url.
See Facebook's debug tool result:
https://developers.facebook.com/tools/debug/sharing/?q=https%3A%2F%2Fcornellreviews-dev-pr-100.herokuapp.com%2F
> Use https for <meta property="og:url" />

- .github/workflows/ci-workflow.yml
- .gitignore
- package.json
This pull request improves the CI setup
See the CI Logs
> Add build step to CI and ensure the CI also runs on master

- imports/ui/Form.jsx
- package-lock.json
Since we require that each review is associated with at least one professor, classes that have no professors associated with them (eg. Span 3440) cannot submit reviews.  This PR allows user to submit a review without a professor ONLY if that class doesn't have any professors associated with it in our DB.
Tested in local, will test in staging then deploy to prod
Fix our Course Roster Scaping algorithm so that every class has at least one professor associated with it.  Not a huge problem now - medium priority.
> Fix required professors for classes with no professors in DB

- imports/ui/CourseCard.jsx
- imports/ui/Form.jsx
- imports/ui/css/CourseCard.css
- imports/ui/js/CourseCard.js
A course's median grade is no longer displayed when looking at its reviews.
> Removed median grade from CourseCard

- imports/ui/ClassView.jsx
- imports/ui/Form.jsx
- server/dbInit.js
- server/methods.js
The popup will now show up ten seconds after a user last typed in the regular review box, if they have typed in it. This was implemented by adding a new field to state in ClassView for the time last time the user typed and a handler that modifies this field to Form's props.
> Leave-a-review popup is delayed while user is typing

- .eslintrc.json
- imports/ui/ClassView.jsx
- imports/ui/Form.jsx
- imports/ui/Review.jsx
- imports/ui/css/Form.css
Implement new tab for closed review form tab.  Used to emphasize the fact that the review form can be opened if it is closed by default. Styling from zeplin doc.  
- New review tab for both opening and closing
- Remove "meteor/no-session" lint check
- Fixed logic to properly display popup every 4 hours
- Change review date timestamp to show semester (eg. FA19)
Tested in local, will test in staging before prod.
> Review tab

- imports/ui/js/Feedback.js
This function is never used. It also looks dangerous since it's using jQuery.
Proof: https://github.com/cornell-dti/course-reviews-react-2.0/search?q=sendFeedback&unscoped_q=sendFeedback
> Remove unused sendFeedback function

- .eslintrc.json
- imports/ui/Auth.jsx
- imports/ui/AuthRedirect.jsx
- imports/ui/CUreviewsGoogleLogin.jsx
- imports/ui/ClassView.jsx
- imports/ui/Course.jsx
- imports/ui/Form.jsx
- imports/ui/Template.jsx
- imports/ui/UpdateReview.jsx
- package-lock.json
- package.json
- server/dbInit.js
- server/methods.js
- server/publications.js
Make the linter slightly stricter and fix linter errors to enable that.
See CI logs. Linter warnings down from 117 to 85.
> Make linter stricter

- imports/ui/js/CourseCard.js
This fixes the bug where top review returns reviews for all classes
Tested locally, will test in staging before pushing to prod
> Fix top review in preview card

- imports/ui/css/Form.css
- imports/ui/css/Navbar.css
This shrinks the height of the banner on the results and class pages.
Tested locally, will test on staging.
> Update banner height

- imports/ui/Accordian.jsx
- imports/ui/Statistics.jsx
- package-lock.json
- package.json
- server/methods.js
Summary:
This pull request adds a chart component that plots the reviews over time of the top 15 majors to the admin dashboard. This allows for an easier way to determine the growth of our site by more easily comparing number of reviews.
Mini changes:
Updated accordion to start closed.
Test Plan:
Tested locally. Can view the chart in the admin dashboard and determine correctness.
Notes:
Chart was created using chartkick (https://chartkick.com/). 
Installed through npm.
Nothing in this pull request should cause problems to existing parts of the site.
> Stats - reviews over time chart 

- imports/ui/FilteredResult.jsx
- imports/ui/PreviewCard.jsx
- imports/ui/ResultsDisplay.jsx
- imports/ui/Review.jsx
This pull request provides documentation for the Results, FilteredResult, ResultsDisplay, PreviewCard, and Review components.
N/A
> Documentation for all the Results page components

- imports/ui/Statistics.jsx
- server/methods.js
This pull request makes the admin chart's range and step changeable. Currently the chart shows data of reviews over a 1 yr interval with a step of 14 days. Now these numbers can freely be manipulated.  
Tested locally by changing the step and range numbers and verifying the result.
> Made admin chart's range and step changeable

- .gitignore
- imports/ui/Form.jsx
- imports/ui/Statistics.jsx
- imports/ui/css/Form.css
This pull request features the new rating-selection functionality and the majority of the styling for CU Reviews's new redesign.
Testing will be done locally by leaving reviews and verifying that the correct data is transmitted and interactivity works as expected.
> form design changes

- client/main.css
- imports/ui/CourseCard.jsx
- imports/ui/css/Form.css
- imports/ui/css/Navbar.css
This PR fixes the following:
-Text centering problem throughout the site
-Ability to submit a review
Tested locally, will test in demo site.
> CSS and Functionality Fix

- imports/ui/ClassView.jsx
- imports/ui/CourseReviews.jsx
- imports/ui/Review.jsx
- imports/ui/css/ClassView.css
- imports/ui/css/CourseReviews.css
- imports/ui/css/Review.css
- package-lock.json
- package.json
This pull request implements some simple styling for reviews on the course page for the blue redesign. This does not include sorting reviews or the complete styling and positioning of text.
QA testing done locally.
> Initial review redesign styling

- imports/ui/Form.jsx
- imports/ui/Review.jsx
- imports/ui/css/Form.css
This PR include incremental changes to review page.  Redesigned review page is not yet done but merging to keep things organized as we finish the redesign implementation.
This is a WIP so no testing occurred.
None
> Redesign review page temp

- imports/ui/FilteredResult.jsx
- imports/ui/Form.jsx
- imports/ui/Gauge.jsx
- imports/ui/PreviewCard.jsx
- imports/ui/SearchBar.jsx
- imports/ui/css/FilteredResult.css
- imports/ui/css/ResultsDisplay.css
- server/methods.js
This pull request provides additional fixes and tweaks to the styling of the results search page, namely some text changes and scrolling functionality. In addition, gauges now load properly on course review pages.
Tested locally through interacting with site.
> Results page fixes

- .meteor/packages
- .meteor/versions
This PR removes the Meteor package `insecure` that is used for testing to "allow all database writes from the client".  This package should never have made it to Prod, shoutout to @SamChou19815 for the catch!
Works locally, nothing changed except for the removal of this package so minimal testing.
> Remove 'insecure' package from Meteor

- imports/ui/ClassView.jsx
- imports/ui/CourseCard.jsx
- imports/ui/CourseReviews.jsx
- imports/ui/css/App.css
- imports/ui/css/ClassView.css
- imports/ui/css/CourseCard.css
- imports/ui/css/CourseReviews.css
- imports/ui/css/Form.css
- imports/ui/js/CourseCard.js
This PR finishes the review page redesign for `blue-redesign`.  See below for screenshots of actual vs design.  Note this does not include redesigned navbar (see #150  for that PR into `blue-redesign`).
Actual:
Design:
Tested for review submitting functionality locally.  Will test as part of `blue-redesign` on dev site.
> Redesign review page

- imports/ui/Gauge.jsx
This fixes the values not showing up for gauges on the review page due to a missing  life cycle method.
Tested locally through opening course review pages.
> Review page gauges fix

- imports/ui/ClassView.jsx
- imports/ui/Navbar.jsx
- imports/ui/Results.jsx
- imports/ui/SearchBar.jsx
This pull request removes placeholder text in the searchbar's input field for the results and review page
Checked locally by navigating to the respective pages
> removing placeholder text from Navbar/Searchbar in results and review page

- imports/ui/PreviewCard.jsx
- imports/ui/Review.jsx
This pull request fixes 
1. The bug on the preview card/review component where professors would appear on a new line.
2. A bug on the preview card where when a class only has 1 review it shows "see 1 more review"
Checked locally to ensure they got fixed
> Fix for professor listed and see more reviews

- imports/ui/Form.jsx
This pull request updates the logo on the auth popup
Checked logo on popup by submitting review
> Popup logo fix

- imports/ui/css/App.css
- imports/ui/css/CourseReviews.css
This pull request aims to fix height bug on ResultsDisplay and the homepage on windows machines
Checked locally
> Windows page fix

- imports/ui/PreviewCard.jsx
- imports/ui/Review.jsx
- imports/ui/css/CourseReviews.css
- imports/ui/css/PreviewCard.css
- imports/ui/css/Review.css
This pull request does the following:
1. Adds more spacing above and below "top rating" text in preview card. Note:  I added the amount specifies in figma, but the gap on the top looks a bit large?
2. Adds more spacing above gauges. 
3. Made prof's names bold in review
4. Added more spacing below date in review
*I saw that text/size changes to gauge was already added in a another PR so i left that out here
Compare with figma designs
> Spacing changes to preview card and review

- client/main.css
- imports/ui/ClassView.jsx
- imports/ui/Gauge.jsx
- imports/ui/PreviewCard.jsx
- imports/ui/Review.jsx
- imports/ui/css/ClassView.css
- imports/ui/css/Form.css
- imports/ui/css/Gauge.css
- imports/ui/css/PreviewCard.css
- imports/ui/css/ResultsDisplay.css
- imports/ui/css/Review.css
This PR changes the default value for a gauge for a class with no reviews from 0 to "-".  It also restyled parts of the results page to adapt to different screen sizes better.
Viewing through different viewports locally
> Results Page Styling and Gauge Default

- imports/ui/Results.jsx
- imports/ui/ResultsDisplay.jsx
This PR changes the top of the results from "We found n courses" to "We found n courses for 'query' ". This was done using the props passed into the Results component.
Tested locally through multiple searches
> Results page now restates query

- imports/ui/css/Review.css
This pull request makes the numbers associated in difficulty, overall, and workload in the review bold.
Checked a review locally to ensure the number is bold
> Bold review nums

- imports/ui/Form.jsx
- imports/ui/ResultsDisplay.jsx
- imports/ui/css/ResultsDisplay.css
- package-lock.json
- package.json
This PR implements a filter for majors in the results page.  Behavior:
- If major search --> disabled
- If keyword search --> accepts multiple majors to filter by with the ability to remove multiple 
Tested locally, will test behavior in review app with team
> Major filter

- imports/ui/SearchBar.jsx
- server/methods.js
This pull request implements a better sorting for search results. This is accomplished through sorting the query results by their minimum edit distance between the course name and the user input.
Tested locally
> Better search

- .github/workflows/ci-workflow.yml
- server/dbInit.ts
- server/methods.test.ts
- server/methods.ts
- server/package.json
- yarn.lock
Developer-friendly testing on the backend. I'm suprised we went this long without proper testing.
This *is* the test plan.
I used the jest framework for this. To cooperate with type-script, I used ts-jest. I found a lovely package: [`mongodb-memory-server` ](https://github.com/nodkz/mongodb-memory-server) which does exactly what we want: Have a clean slate local mongodb server running, which we can talk to during our unit tests.
Also there's a little fix for one of the backend functions.
> Introducing Unit Testing

- .gitignore
- client/package.json
- client/src/meteor-shim.ts
- client/src/ui/Statistics.tsx
- server/methods.ts
- yarn.lock
This pull request resolves the issues that caused the graph to not load.
The issue was related to promises in the backend and changes to mongo that did not allow certain forms of queries.
This pull request also resolves the `b is not a function` when navigating to the admin page by updating `react-google-login`
Checked locally by navigating to /admin
There was a lot of issues with the following proxy error:
```
Proxy error: Could not proxy request /methods/getReviewsOverTimeTop15 from localhost:3000 to http://localhost:8080.
See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNRESET).
```
As of this pull request, this error appears only once the first time you navigate to /admin. Previously, the moment you went to /admin the chart would begin to …
> Resolving some graph errors

- client/src/ui/Login.tsx
- client/src/ui/Statistics.tsx
This PR fixes a flaky step in the authentication of the `/admin` path.
Issue was: the Session variable `adminlogin` was not being reset if a `token` was outdated - this resulting in users being able to access the admin page but leading to issues once on the page because their admin token was out of date
Tested workflow locally. Will test on dev server.
I advise that after this is merged, all current branches should be rebased on top of `master` to make sure these issues are fixed while working on updates to the admin page
> Admin Page Auth Issues

- server/methods.ts
- server/shim.ts
This PR adds error handling on the back-end to all functions in `server/methods.ts`.  These exist in the form of `try/catch` statements that prints <ins>on the server's log</ins> where a function fails and the full `error` object caught as a result.
Ideally, this error handling should be automated for all calls to the back - but since we're still using the `server/shim.ts` and `client/meteor-shim.ts` files for these calls, I figured we could implement this at the individual method level for now.
Tested locally - found a successful case where a function failed and was caught and logged on the backend.  Will test functionality on dev site
> Error handling

- client/src/ui/Form.jsx
- client/src/ui/Review.jsx
- client/src/ui/css/Form.css
- client/src/ui/css/Review.css
- server/dbDefs.ts
- server/methods.ts
This pull request builds upon initial work for dealing with reviews affected by the pandemic.
Tested locally through creating reviews with and without the COVID checkbox checked and verifying if tag does or does not show up after approval
Currently whether or not the checkbox is shown is determined by a hard coded boolean, we may want to move this to the admin dashboard or a config.
> Covid reviews

- client/src/ui/Admin.jsx
- client/src/ui/CourseReviews.tsx
- client/src/ui/RecentReview.tsx
- client/src/ui/UpdateReview.tsx
- server/methods.ts
This pull request updates the back end so that "updateCourseMetrics" is called for when reviews are removed from the admin page so the metrics are updated. In addition, when a user reports a review, it will disappear from the UI without refreshing
Tested locally through front end and print statements.
> Metrics update after undoing report and reviews disappear after reporting

- common/CourseCard.js
- server/server.ts
See issue #199 . There was a problem were NaNs were introduced when computing gauge values. This should fix that problem, or at least it does for my local replication of the problem.
1. Create a server with a mongodb url pointing to dev db.
2. Create a review on a class with reviews which have NaNs. I used CS 2112, which failed before.
3. Approve Review
4. Confirm there are no problems
None
None
> Fix Issue #199

- server/endpoints.test.ts
- server/endpoints.ts
- server/endpoints/SearchBar.test.ts
- server/endpoints/SearchBar.ts
- server/methods.ts
- server/package.json
- server/server.ts
- server/tsconfig.json
- yarn.lock
This pull request is the first step towards deprecating the Meteor Shim on the backend
This PR:
* Creates an example endpoint to pattern other after
* Sets up a small framework which abstracts away boiler-plate code
* Sets up testing for the newly created endpoints
This is a draft pull request while we decide if this is a good pattern, and if there are any things about the pattern that we want to change.
Write tests for the endpoints. See endpoints.tests.ts
TODO: Discuss the merits.
None. Deprecation will come later.
> Create example pure express.js endpoint

- common/index.d.ts
- server/endpoints.ts
- server/endpoints/Auth.test.ts
- server/endpoints/Review.test.ts
- server/endpoints/Review.ts
- server/endpoints/utils.ts
This pull request adapts the endpoint for inserting reviews. It turns out that inserting reviews requires inserting users so this PR adapts that as well. 
Tests are in Review.test.ts. Tested inserting review and user by asserting that the new user and review are in the db.
Currently I have put the endpoint for inserting users in Review.ts but we can move it when we decide on a structure.
> Express endpoints for inserting reviews and Users

- client/src/ui/Accordian.tsx
- client/src/ui/Statistics.tsx
- server/methods.ts
This pull request adds a button to "/admin" that downloads a csv which contains review data for courses.
Tested manually by clicking on button
> Adding a download CSV Button for reviews per class  

- client/src/ui/Admin.jsx
- client/src/ui/UpdateReview.tsx
Changes Admin review page to display reviews based on state, not props, and uses this to remove reviews from view after they've been approved or removed.
Tested locally through approving, removing, and unreporting reviews on the admin page.
Took a long time to update when running locally but I believe this was due to the backend call taking a long time.
N/A
> Admin live behavior

- client/src/ui/ClassView.jsx
- client/src/ui/Form.jsx
- client/src/ui/SearchBar.jsx
- client/src/ui/SubjectLeaderboard.tsx
- common/CourseCard.js
- server/endpoints/AdminActions.test.ts
- server/endpoints/AdminActions.ts
This PR fixes linter warnings in SubjectLeaderBoard, CourseCard, AdminActions, AdminActions.test.
*This is the 2nd PR for the clean code dev sesh event.
> More Linter warning fixes

- README.md
Update README for SP21/FA20 semesters. More updates likely as we onboard more members!
> Update README for SP21/FA20 semesters

- client/src/ui/Form.jsx
- server/endpoints.ts
- server/endpoints/AdminActions.test.ts
- server/endpoints/AdminActions.ts
- server/server.ts
This pull request updates the function **submitReviews** from Forms.jsx (client) to use axios and renames the diffculty field of the object **newReviews** from _diff_ to _difficulty_ to match the fields.
Test locally - I submitted a review and checked that it went through successfully
> Updated submitReviews to use axios 

- client/src/ui/ClassView.jsx
- client/src/ui/CourseReviews.tsx
- client/src/ui/PreviewCard.jsx
- client/src/ui/RecentReview.tsx
- client/src/ui/Review.jsx
- client/src/ui/UpdateReview.tsx
This PR migrates the following methods to the new backend functionality.
- getCourseById
- getCourseByInfo
- getReviewsByCourseId
Tested locally by verifying that looking at classes still works as intended.
> Course fetching migration

- client/src/ui/Admin.jsx
- client/src/ui/Login.tsx
- server/endpoints/AdminActions.test.ts
- server/endpoints/AdminActions.ts
This pull request updates the frontend to use axios to call the **makeReviewVisible** and **tokenIsAdmin** endpoints.
Tested **makeReviewVisible** by posting a review and accepting it in the admin panel. Then the course page was checked to see if the review appeared.
Tested **tokenIsAdmin** by un-admining myself and navigating to "/admin".
> Authentication and review visibility frontend axios migration 

- client/src/ui/SearchBar.jsx
- server/endpoints/Review.test.ts
- server/endpoints/Search.test.ts
- Added testing cases that check for queries with no matching results, queries containing non-ascii characters, and queries with subject and number combined (with no space) for **Search.test.ts**
- Added a testing case that calls the method _decrementLikes_ for **Review.test.ts**
- Updated the log message from "getting subjects failed" to "getting professors failed" for the axios call '/v2/getProfessorsByQuery' from **SearchBar.jsx**
Newly added tests all passed
> Added Testings

- client/src/index.tsx
- client/src/ui/Admin.jsx
- client/src/ui/ClassView.jsx
- client/src/ui/CourseCard.tsx
- client/src/ui/CourseReviews.tsx
- server/endpoints.ts
- server/endpoints/AdminActions.test.ts
- server/endpoints/AdminActions.ts
The time has come to remove Meteor subscriptions. If you want to know why, just take a gander into [`publications.ts`](https://github.com/cornell-dti/course-reviews-react-2.0/blob/master/server/publications.ts). It's pretty bad.
For those things which I thought make sense, we should actually have preserved the live update ability (though I have not tested this all to thoroughly).
Tested locally. Verified tests still pass.
I had to add a new backend endpoint, because of the way subscriptions work, the Admin page was fetching the relevant reviews through a subscription, and not an endpoint call. 
None, everything should still work.
> No more subscriptions.

- client/public/index.html
- client/src/ui/Admin.jsx
- client/src/ui/CourseReviews.tsx
- client/src/ui/FilteredResult.tsx
- client/src/ui/Form.jsx
- client/src/ui/Login.tsx
- client/src/ui/Results.jsx
- client/src/ui/ResultsDisplay.jsx
- client/src/ui/SearchBar.jsx
- client/src/ui/css/FilteredResult.css
- client/src/ui/css/ResultsDisplay.css
- server/endpoints.ts
- server/endpoints/AdminActions.test.ts
- server/endpoints/AdminActions.ts
- server/endpoints/Review.test.ts
- server/endpoints/Review.ts
- server/endpoints/Search.test.ts
- server/endpoints/Search.ts
This PR updates the search results page for mobile. More specifically the padding, margins, cards, and border around overall rating for the page were tackled in this PR. The filter button, the top portion of the page (search bar) have not been touched in this PR. Let me know if i missed anything.
Checked locally by pulling up the page
Some of the figma numbers seemed off (especially the border padding for the overall rating) so i eye-balled it.
> Search results page for mobile 

- client/package.json
- client/src/ui/Form.jsx
- client/src/ui/css/customToast.css
- yarn.lock
Submitting a review now results in either a success or error toast notification, as opposed to alert popups that were used previously.
Tested on successful course review submissions
> Used react-toastify for new notifications

- client/src/ui/css/Navbar.css
- client/src/ui/css/SearchBar.css
- Changed the navbar so the logo disappears on mobile 
- Changed the size and margins of the search bar to match the mobile design 
I ran the program locally with 375 x 812 size
> Modify SearchBar and NavBar for Mobile (new)

- client/src/ui/CourseReviews.tsx
- client/src/ui/Review.jsx
- common/index.d.ts
- server/dbDefs.ts
- server/endpoints/Review.test.ts
- server/endpoints/Review.ts
This PR updates schema of `review` and `student` to allow for tracking of likes/dislikes and updates the `incrementLike` and `decrementLike` functions to handle the changes.
A small bug dealing with an onScroll function being undefined in desktop was also fixed.
Tested locally by liking/disliking.
> Like/Dislike tracking + frontend bug fix

- client/src/ui/CourseReviews.tsx
- client/src/ui/Form.jsx
- client/src/ui/ResultsDisplayMobile.tsx
- client/src/ui/Review.jsx
- server/endpoints/Review.ts
- server/endpoints/Search.test.ts
- server/endpoints/Search.ts
This PR fixes ~~3~~ 4 issues:
- #230 
- #266 
- An issue where sometimes reviews on the admin page would be duplicated.
- An issue where the screen width was not being computed properly.
Adjusted unit tests for search. Made sure everything else still works locally.
None
None
> Small bugfixes

- client/src/ui/ResultsDisplay.jsx
This PR removes the major search function
Testing locally and the filter function still works as intended
> removed major search

- client/src/ui/css/ResultsDisplay.css
This pull request adds 8px bottom padding to dropdown menu
Ran locally
> Small padding fix to dropdown menu

- server/endpoints.ts
- server/endpoints/Profile.test.ts
- server/endpoints/Profile.ts
I created a new endpoint _getTotalLikesByStudentId_ that takes a student's net id and returns the total number of likes the student has gotten on their reviews.
I created a test file with testing data of students and reviews and checked that the endpoint correctly returns the total number of likes.
> Counting total number of likes on a student's reviews

- README.md
> Updated ReadME with 2022 Developers

- server/endpoints.ts
- server/endpoints/Profile.test.ts
- server/endpoints/Profile.ts
This PR added an endpoint [getReviewsByStudentId] in Profile.ts that returns the list of Review objects for the given student's netID. 
Tested locally. Since there is a discrepancy between the test review objects and review objects generated by the database, the number of returned reviews is compared for convenience.
> Get Reviews by Student

- client/src/ui/CourseReviews2.tsx
- client/src/ui/Profile.tsx
- client/src/ui/css/Profile.module.css
- server/endpoints.ts
- server/endpoints/Profile.ts
This PR is the first part of the display of the past reviews on the profile page. This PR handles the case where a student has written at least one review in the past. There will be separate PRs for the case where there is no review or there is at least one pending review.
tested locally with a student that has past reviews
> Right profile page [1/2]

- server/endpoints.ts
This pull request is meant to register the setProfessors endpoint so it can be used in the Admin page.
> register setProfessors endpoint

- client/src/auth_utils.ts
- client/src/ui/Admin.jsx
- client/src/ui/Login.tsx
- server/dbInit.ts
- server/endpoints.ts
- server/endpoints/AdminActions.ts
This pull request fixes the update professors button on the admin page by discarding expired tokens and refetching them.
I tested this with user testing.
No linter warnings.
- This PR fixes authentication on the admin page, but does not address it on the main site. It should probably be followed by another PR to fix authentication across the site.
> Fixing Update Professors

- client/src/ui/Profile.tsx
- server/endpoints.ts
- server/endpoints/Profile.ts
- server/endpoints/utils.ts
This pull request is the first step towards implementing feature Foo
I ran the code on my laptop and the data displays on my browser.
> updated linking authentication

- client/src/ui/css/ProfileDropdownNavBar.module.css
Fixed profile bear on mobile so it doesn't show up. If it's there, it's duplicated functionality. 
Before this PR (i.e. on the main branch), there are X linter warnings. After my PR, there are Y.
> Fixed profile bear on mobile 

- README.md
Putting names of members in READMe.md
> Update README.md with Names of Members

- client/src/ui/Profile.tsx
- client/src/ui/css/Profile.module.css
This PR fixes the sorting of reviews on the profile page and also fixes the hide pending reviews button.
Tested locally on laptop. Since client keeps making bad requests to server, I just hard coded `http://localhost:8080` to run the code properly. 
Before this PR (i.e. on the main branch), there are X linter warnings. After my PR, there are Y.
> Fix profile sorting and hide pending reviews button

- client/src/auth/auth_utils.ts
- client/src/ui/Navbar.tsx
- client/src/ui/Review.tsx
- client/src/ui/ReviewForm.tsx
- server/endpoints.ts
- server/endpoints/Review.test.ts
- server/endpoints/Review.ts
This PR fixes the like button.
> Fixing Like Button

- client/src/ui/ClassViewNew.tsx
- client/src/ui/Profile.tsx
- client/src/ui/ReviewForm.tsx
There were some bugs on the profile page like sorting by recent reviews and submitting a new review used to both throw errors, but should be fixed now.
Before this PR (i.e. on the main branch), there are X linter warnings. After my PR, there are Y.
> fixed bugs from profile page

- client/src/auth/auth_utils.ts
This PR adds comments to document the new authentication process.
> Auth Comments

- .github/workflows/ci-workflow.yml
- client/package.json
- package.json
Specifies the node version when building on heroku, so hopefully, build will stop failing.
> Specify node build version

- README.md
> adding myself to readme

- client/src/index.css
- client/src/modules/Course/Components/Course.tsx
- client/src/modules/Course/Styles/Course.module.css
- client/src/modules/Course/Styles/ReviewForm.module.css
According to Maywa's designs - changing the font to SF Pro (apple-system font which falls back to sans-serif). May actually need to install it as a web font if it does not display the same on a Windows machine. 
- CSS Reset (some global CSS changes to make future styling easier 
- Remove the Mobile Metrics view (buggy right now) - also the course reviews is not sticky rn 
- CSS files are sort of messy and have a lot of unnecessary lines. ( Looks like copied from Figma ) ie. font is constantly re-defined when not needed. 
- I would love to redo the CSS Styling in the future ( new dev task o.o ) - get rid of any bootstrap classes so we don't have to rely on it anymore (has a lot of built-in margins/paddings/spacing makes it hard to style properly.)
- The sign-in button is blocked by the …
> Typography Change & Tiny CSS Reset

- README.md
add myself as developer, Andrea as designer, and Jonathan as product manager to the README
> add myself, andrea, and jonathan to README

- .github/PULL_REQUEST_TEMPLATE.md
- README.md
- client/src/modules/Home/Home.module.css
- package.json
- new PR template 
- fix login button to display on mobile devices 
- new dev scripts 
```bash
yarn client 
```
& 
```bash
yarn server
```
> Mobile Login Reappear, PR Template, and new dev Scripts 

- README.md
None
Updated ReadMe file
[gif](https://media2.giphy.com/media/v1.Y2lkPTc5MGI3NjExOWd4OHF2OGp0eHN0cTV4aG4xZnJ0bTRrZGgzamdqam8yYTM3a2Y4byZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/3oz8xrJM0xKZ8o1gcw/giphy.gif)
> Updated ReadMe with name

- README.md
No test plan necessary
Updated README.md
[gif](https://media.tenor.com/D9URs5DH-gUAAAAM/funny.gif)
> Update README with Remaining Newbies

- client/src/auth/auth_utils.ts
- client/src/modules/Admin/Components/Admin.tsx
- client/src/modules/Course/Components/Course.tsx
- client/src/modules/Course/Components/PreviewReviewCard.tsx
- client/src/modules/Course/Components/ReviewCard.tsx
- client/src/modules/Globals/Navbar.tsx
- client/src/modules/Home/Components/Home.tsx
- client/src/modules/Profile/Component/Profile.tsx
This PR works on the authentication feature.
Login to CU Reviews website and ensure the following pages are still functional:
- Home
- Profile
- Courses
- Reviews
- Leaving Reviews Card
- Changed auth util functions to object representations
- Added documentation to auth util functions
[gif](https://living.acg.aaa.com/content/dam/aaa-living/devtest/what-is-two-factor-authentication.gif)
> Auth Utils Functions to Objects

- client/src/modules/Admin/Components/Admin.tsx
- client/src/modules/Course/Components/Course.tsx
- client/src/modules/Globals/Loading.tsx
- client/src/modules/Globals/Styles/Loading.module.css
- client/src/modules/Profile/Component/Profile.tsx
- client/src/modules/Results/Components/ResultsDisplay.jsx
This PR works on the Loading feature.
- [] 📝 Documentation Update
Checked to make sure that loading screen is updated with new wheel in all screens: Course screen, Home screen, Admin screen
Loading wheel graphics can be updated by changing CSS files with new design choices
> Loading screen update

- client/src/modules/Course/Components/ReviewModal.tsx
This PR fixes the typo on the `ReviewModal.tsx` from "porofessor" to "professor"
> "Professor" Typo Fix

- .github/workflows/ci-workflow.yml
- client/package.json
- client/src/modules/Course/Components/Course.tsx
- client/src/modules/Course/Components/PreviewReviewCard.tsx
- package.json
- server/endpoints.ts
- server/package.json
- server/src/ai/ai.functions.ts
- server/src/ai/ai.router.ts
- yarn.lock
This PR works on the Cornellians Say feature. OpenAI needs newer node versions and typescripts so this upgrades to node 18 as well as integrates OpenAI and endpoints for the summarizing feature. 
> Upgrading to Node 18 + OpenAI AI Router created

- package.json
Removes NPM from our engines. ( we use yarn ) 
> Remove NPM Engine

- client/src/auth/auth_utils.ts
- client/src/modules/Profile/Component/Profile.tsx
This fixes any page that requires authentication or tokens. 
At least will fix the reviews you made on your profile page to show up. 
> Fix AuthLogin Bug (null token name)

- client/src/modules/Profile/Component/Profile.tsx
> Fixed review endpoint not working

- client/src/modules/Profile/Component/Profile.tsx
- client/src/modules/Profile/Component/ProfileCard.tsx
- client/src/modules/Profile/Component/UserInfo.tsx
This PR works on the broken Profile page feature
> quick fix to restore profile function

- client/src/modules/Profile/Component/UserInfo.tsx
> fixed variable name

- client/src/modules/Admin/Components/Admin.tsx
- client/src/modules/Course/Components/Course.tsx
- server/scripts/populate-courses.ts
This PR works on adding new semester data into the Course database.
Added SP25 and sorted semester list:
- All SP25 courses should be updated in staging DB
- Hard-coded new semester(s) to add
- Sorted semester list so that most recent semester is at the end of the list
> Add New Semester

- server/scripts/populate-courses.ts
This PR works on the Similar Courses tag feature.
- search up PMA 1141 in the staging db and the first tag should be changed to the format: "Overall: _/5"
- changed rating tag to "Overall: _/5" to match design in Figma
> Update tag content to match figma

- client/src/modules/Admin/Components/Admin.tsx
- client/src/modules/Admin/Components/AdminReview.tsx
- client/src/modules/Admin/Components/ManageAdminModal.tsx
- client/src/modules/Admin/Components/Stats.tsx
- server/src/admin/admin.controller.ts
- server/src/admin/admin.data-access.ts
- server/src/admin/admin.router.ts
This PR works on the documentation feature.
Added documentation to admin-related files in the codebase and changed to arrow functions
> Documentation for Admin page

- client/src/modules/Admin/Components/Admin.tsx
> fixed an endpoint

- README.md
This PR works on the README.
Read the README
Read the README
Read the README
README
> Update README with FA24 team roster

- client/src/modules/Admin/Components/Admin.tsx
- server/server.ts
- server/src/admin/admin.controller.ts
- server/src/admin/admin.data-access.ts
- server/src/admin/admin.router.ts
This PR works on implementing picking a raffle winner.
Uses the point system from the Fall 2024 raffle. 
Only bad thing about this code is that it doesn't remove an entry when a user wins.  [ so its like sampling without replacement ] 
[gif](https://media0.giphy.com/media/TvC6B8iS2VUXGk9IEs/giphy.gif?cid=6c09b952ck9hwgljlkm817sz1wq4gc3i3ol4wp4wg146f1g7&ep=v1_internal_gif_by_id&rid=giphy.gif&ct=g)
> Pick a Raffle Winner 

- client/src/modules/Course/Components/CornelliansSay.tsx
make sure all adjectives on tags are uppercase
> fix capitalization issue

- client/src/modules/Course/Components/MultiSelect.tsx
- client/src/modules/Course/Styles/Select.module.css
This PR works on the review modal feature.
Before searching:
During searching:
Click inside the prof or major box in the review modal and search
Added searching for profs/majors
> Type to Search for Profs and Majors

- README.md
> Update all semester rosters

- client/src/modules/Course/Components/Course.tsx
- client/src/modules/Course/Components/CourseReviews.tsx
- client/src/modules/Course/Components/Feedback.js
- client/src/modules/Course/Components/PreviewReviewCard.tsx
- client/src/modules/Course/Components/RatingInput.tsx
- client/src/modules/Course/Components/ReviewCard.tsx
- client/src/modules/Course/Components/ReviewModal.tsx
- client/src/modules/Course/Components/SimilarCoursesCard.tsx
- server/src/course/course.controller.ts
- server/src/course/course.recalgo.ts
This PR updates documentation for the Course module.
- Update documentation for Course modules
- Change all functions to arrow functions
> Update course files

- client/src/modules/Globals/majors.ts
> added MBA for cornell tech

- server/src/admin/admin.controller.ts
This PR works on the similar courses feature. This is a temporary change that removes error checking to attempt to complete course recommendation database population. Will be reverted after
> removing error checks

- server/src/admin/admin.controller.ts
This PR skips description processing so we can move straight to developing IDF vectors.
> skipping desc processing

- client/src/modules/Admin/Components/AdminReview.tsx
- client/src/modules/Admin/Components/DevTools.tsx
- client/src/modules/Admin/Components/Dropdown.tsx
- client/src/modules/Admin/Components/Reviews.tsx
- client/src/modules/Admin/Styles/Dropdown.module.css
- client/src/modules/Admin/Styles/NewAdmin.module.css
- client/src/modules/Course/Components/Course.tsx
- client/src/modules/Course/Components/ReviewCard.tsx
- server/db/schema.ts
- server/scripts/populate-course-evals.ts
- server/scripts/populate-courses.ts
- server/src/admin/admin.controller.ts
- server/src/admin/admin.router.ts
- server/src/course/course.controller.ts
- server/src/course/course.data-access.ts
- server/src/course/course.router.ts
- server/tests/Course.test.ts
- server/tests/TestServer.ts
This PR works on the similar courses feature: it temporarily turns off the other steps in the process (idf vector generation, etc.) in order to simply focus on the similarity adding - in the future, will create separate endpoints for these functions because they each take a long time. Additionally, it adds more error checking so that the function does not crash when met with a single error.
> turning off all commands except add similar courses

- server/scripts/populate-courses.ts
This PR works on the similar courses feature. Trying to fix because there are not exactly as many recommendation metadata as courses in the db... not sure why tho
> error catching

- client/src/modules/Admin/Components/AddAdminModal.tsx
- client/src/modules/Admin/Components/AdminUsers.tsx
- client/src/modules/Admin/Styles/AddAdminModal.module.css
- client/src/modules/Admin/Styles/ManageAdmins.module.css
- common/index.d.ts
- server/db/schema.ts
- server/src/admin/admin.controller.ts
- server/src/admin/admin.data-access.ts
- server/src/admin/admin.router.ts
- server/src/admin/admin.type.ts
- server/src/auth/auth.type.ts
This PR works on the Admin Page feature.
Tested adding different admins and checked whether they show up on the list of admins on the page as well as whether they are updated with the correct privilege and role in the database. 
-added new field in student for role (only appears in students with admin privilege)
-added a modal with the form to add a new admin
> Manage Admin Page Add Admin

- client/src/modules/Admin/Components/DevTools.tsx
- client/src/modules/Admin/Styles/DevTools.module.css
> pushing dropdown for semester select

- client/src/modules/Admin/Components/DevTools.tsx
- server/src/admin/admin.router.ts
> cleaning up

- client/src/modules/Admin/Components/DevTools.tsx
This PR works on the semester update feature.
> added more semesters

- server/scripts/populate-course-evals.ts
> reset all course evals

- server/src/admin/admin.controller.ts
> turn off other functions

- client/src/modules/Course/Components/Course.tsx
This PR works on the sort feature.
> default sort is now by recent

- client/src/modules/Admin/Components/Stats.tsx
- client/src/modules/Course/Components/Course.tsx
> remove redundant info from stats

- server/src/admin/admin.controller.ts
- server/src/admin/admin.router.ts
This PR works on fixing the vulnerability in Issue #539.
> Implemented admin check for raffle
